export const strings = {
  title: "Confirmar Asistencia",
  description:
    "Estamos emocionados de celebrar este dia tan especial junto a ti, por favor dejanos saber si podras asistir.",
  eventDate: "2025-09-28", 
  eventDateLabel: "Fecha De Evento",
  eventLocation: "la bebe, Granjas Santa Cecilia, 21386 Mexicali, B.C., Mexico",
  eventLocationLabel: "Event Location",
  nameLabel: "Nombre",
  emailLabel: "Numero de Telefono",
  accompanyLabel: "Numero De Invitados",
  rsvpLabel: "Confirmar Asistencia?",
  yesOption: "Si",
  noOption: "No",
  submitButton: "Confirmar Asistencia",
  thankYouMessage: "Gracias por confirmar tu asistencia!",
  viewOnMapButton: "Ver ubicación en Google Maps",
  sendFromEmail: "dodgerblue23@icloud.com",
  sendToEmail: process.env.EMAIL_TO,
};
